String reverse
Hargeon/stringhlp pull request #1
Opened 2021-08-30 14:06 UTC by Hargeon

Added tests and implemented Reverse function

2021-08-30 15:21 UTC, gordonBusyman requested changes
Looks good! 
Please address the comments. Also I highly recommend to rename the pkg

2021-08-30 15:21 UTC, gordonBusyman commented on strings_helper.go
> +// CharNumber returns a number of characters in the string
This function is not required for the first release

2021-08-30 15:21 UTC, gordonBusyman commented on strings_helper.go
> +// Reverse string
Can we a add a more descriptive comment

2021-08-30 15:21 UTC, gordonBusyman commented on strings_helper.go
> +func Reverse(str string) string {
Use new lines to separate the logical code blocks if you _want_

2021-08-30 15:21 UTC, gordonBusyman commented on strings_helper_test.go
> +func TestReverse(t *testing.T) {
Add `t.Run()` for test cases with the name of the test (what is being tested)

2021-08-30 15:21 UTC, gordonBusyman commented on strings_helper_test.go
> +		},
Add one more test to check the phrase, ex: "Мама мыла раму"

2021-08-30 15:21 UTC, gordonBusyman commented on strings_helper_test.go
> +			t.Errorf("For case %v expected: %v, got: %v\n", testCase.input, result, testCase.result)
In this case formatter %q  is more appropriate, ex.: `For case "" expected: "", got: "r"` is the message for failed the case [here](https://github.com/Hargeon/strings_helper/blob/e3c9828853a42f5181edd85c1db689612650f781/strings_helper_test.go#L25)

2021-08-30 16:51 UTC, Hargeon commented on .idea/.gitignore
> +.idea
Fixed in new commit

2021-08-30 16:51 UTC, Hargeon commented on README.md
> +Task:
Fixed in new commit

2021-08-30 16:51 UTC, Hargeon commented on go.mod
> +module "github.com/Hargeon/strings_helper"
Fixed in new commit

2021-08-30 16:51 UTC, Hargeon commented on strings_helper.go
> +package strings_helper
Fixed in new commit

2021-08-30 16:52 UTC, Hargeon commented on strings_helper.go
> +// Reverse string
Fixed in new commit

2021-08-30 16:52 UTC, Hargeon commented on strings_helper.go
> +func Reverse(str string) string {
Fixed in new commit

2021-08-30 16:52 UTC, Hargeon commented on strings_helper_test.go
> +func TestReverse(t *testing.T) {
Fixed in new commit

2021-08-30 16:52 UTC, Hargeon commented on strings_helper_test.go
> +		},
Fixed in new commit

2021-08-30 16:53 UTC, Hargeon commented on strings_helper_test.go
> +			t.Errorf("For case %v expected: %v, got: %v\n", testCase.input, result, testCase.result)
Fixed in new commit

2021-08-30 16:58 UTC, gordonBusyman commented on .idea/.gitignore
> +.idea
Please remove this

2021-08-30 17:00 UTC, gordonBusyman commented on README.md
> +# stringhlp - helper for string manipulation
Looks good^ but please add more details described in https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes

2021-08-30 17:01 UTC, gordonBusyman commented on strings_helper.go
> +// CharNumber returns a number of characters in the string
Please pay attention to this comment

2021-08-30 17:04 UTC, gordonBusyman commented on strings_helper_test.go
> +		t.Run(testCase.input, testReverseFunc(testCase.input, testCase.result))
Usually for the name of the test case we use another property "name", like:
```
...
		{
                        name: "None ASCII phrase",
			input:  "Мама мыла раму",
			result: "умар алым амаМ",
		},
...
t.Run(testCase.name, testReverseFunc(testCase.input, testCase.result))
...
```

2021-08-30 17:06 UTC, gordonBusyman commented on strings_helper_test.go
> +}
This is the example that can be moved to README _(as you already have done)_

2021-08-30 18:11 UTC, Hargeon commented on .idea/.gitignore
> +.idea
Done

2021-08-30 18:12 UTC, Hargeon commented on strings_helper.go
> +// CharNumber returns a number of characters in the string
Commented the method

2021-08-30 18:12 UTC, Hargeon commented on README.md
> +# stringhlp - helper for string manipulation
Done

2021-08-30 18:12 UTC, Hargeon commented on strings_helper_test.go
> +		t.Run(testCase.input, testReverseFunc(testCase.input, testCase.result))
Done

2021-08-30 18:12 UTC, Hargeon commented on strings_helper_test.go
> +}
Done

2021-08-30 20:14 UTC, gordonBusyman commented on .gitignore
> +.idea
[Here](https://github.com/github/gitignore) you can find examples of correct `.gitignore` files

2021-08-30 20:15 UTC, gordonBusyman commented on README.md
> +go get -u github.com/Hargeon/stringhlp
What is the `-u` flag for?

2021-08-30 20:16 UTC, gordonBusyman commented
Please remove the `./idea` folder - it is empty

2021-08-30 20:17 UTC, gordonBusyman requested changes
Left final comments. This is it and we are gtg

2021-08-31 12:38 UTC, Hargeon commented on .gitignore
> +.idea
Done

2021-08-31 12:41 UTC, Hargeon commented on README.md
> +go get -u github.com/Hargeon/stringhlp
The flag helps to upgrade to a new minor version if someone is already using the old one

2021-08-31 12:46 UTC, gordonBusyman approved these changes

2021-08-31 12:49 UTC, merged